### ISSUE TITLE
VM Module does not have an option to specify/modify secret name for VM password

### ISSUE THREAD

**Issue by msmit-CN** [CloudNationHQ/terraform-azure-vm#108]
CN VM module automatically includes the creation of a random password, after which a key vault secret is created. Currently, this way of working does not allow for the modification of the name of this secret. It is possible with workarounds to accomplish this, but might be nice to have the option in the module itself?

**Comment by eddy-vera** [comment]
@msmit-CN: Please check https://github.com/CloudNationHQ/terraform-azure-vm/tree/main/examples/authentication#usage-bringing-your-own-password-or-ssh-key
You can bring your own password or SSH key from (e.g.) the KV Module, and specify your own naming there.
