### ISSUE TITLE
[BUG] - random provider version constraint too strict

### ISSUE THREAD

**Issue by cveld** [CloudNationHQ/terraform-azure-vm#121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Module Version

2.2.0

### Terraform Version

1.8.1

### AzureRM Provider Version

3.110.0

### Short Description

random version constraint too strict

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
  }
}
```

### Expected Behaviour

The combination of the `~> 3.6` constraint and consuming the vm module should just work.

### Actual Behaviour

This combination yields the following error:

```
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider
│ hashicorp/random: locked provider registry.terraform.io/hashicorp/random
│ 3.5.1 does not match configured version constraint >= 3.3.2, >= 3.5.1, ~>
│ 3.5.1, ~> 3.6, < 4.0.0; must use terraform init -upgrade to allow selection
│ of new versions
╵
```

As `~> 3.5.1` tells terraform to cap on everything `< 3.6.0`. Refer to: https://developer.hashicorp.com/terraform/language/expressions/version-constraints

### Steps to Reproduce

1. `terraform apply`

**Comment by eddy-vera** [comment]
We choose not to create a seperate issue for each module, but to use a generic instead, see: https://github.com/CloudNationHQ/terraform-azure-sa/issues/83
