### ISSUE TITLE
Add support for computer_name as optional value

### ISSUE THREAD

**Issue by eddy-vera** [CloudNationHQ/terraform-azure-vm#25]
- [computer_name] - (Optional) Specifies the Hostname which should be used for this Virtual Machine. If unspecified this defaults to the value for the name field. If the value of the name field is not a valid computer_name, then you must specify computer_name. Changing this forces a new resource to be created.

This is needed to have longer (than 15 characters) names of the VM resource,  as hostnames in Windows only are allowed up to 15 characters. For naming conventions this can be necessary.

**Comment by dkooll** [comment]
solved by #26
